apiVersion: v2
name: go-web-app-chart
description: A Helm chart for Kubernetes

# Chart type: application or library
type: application

# Chart version (bump this whenever you change chart files)
version: 0.1.1

# Application version (should match your image tag)
appVersion: "22021258872"
